#!/bin/bash

log() {
  local type="$1"; shift
  local msg="$*"

  case "$type" in
    INFO)    printf "\033[1;34m[INFO]\033[0m %s\n" "$msg" ;;
    WARN)    printf "\033[1;33m[WARN]\033[0m %s\n" "$msg" ;;
    ERROR)   printf "\033[1;31m[ERROR]\033[0m %s\n" "$msg" ;;
    DEBUG)   printf "\033[1;90m[DEBUG]\033[0m %s\n" "$msg" ;;
    SUCCESS) printf "\033[1;32m[SUCCESS]\033[0m %s\n" "$msg" ;;
    *)       printf "[LOG] %s\n" "$msg" ;;
  esac
}
