#!/bin/bash

run_npm() {

  # Check for npm
  if ! type_exists 'npm'; then
    printf "\n"
    e_header "npm not found, installing..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install --lts
    nvm use --lts
  else
    log INFO "NVM already installed"
  fi

  #e_header "Installing Node.js packages..."

  # List of npm packages
  #local packages="bower grunt grunt-cli karma yo"

  # Install packages globally and quietly
  #npm install $packages --global --quiet

  [[ $? -eq 0 ]] && e_success "Done"

}
